// Generated by https://quicktype.io

export interface User {
  id:                    number;
  username:              string;
  password:              string;
  accessId:              string;
  email:                 string;
  name:                  string;
  lastName:              string;
  role:                  string;
  sessions:              Session[];
  accountNonLocked:      boolean;
  accountNonExpired:     boolean;
  credentialsNonExpired: boolean;
  enabled:               boolean;
  failedAttempts:        number;
  lockTime:              null;
}

export interface Session {
  id:                number;
  jwt:               string;
  fechaInicioSesion: string;
  fechaFinSesion:    null;
}
